"""Initial clean migration

Revision ID: 2197d5a876d3
Revises: 9509e1f4b3a6
Create Date: 2025-07-24 03:04:02.476140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2197d5a876d3'
down_revision = '9509e1f4b3a6'
branch_labels = None
depends_on = None

def upgrade():
    # Ensure indexes exist on referenced columns before applying foreign keys
    op.create_index('ix_items_item_id', 'items', ['item_id'])
    op.create_index('ix_suppliers_supplier_id', 'suppliers', ['supplier_id'])

    # Create purchases table
    op.create_table(
        'purchases',
        sa.Column('purchase_id', sa.String(length=36), nullable=False),
        sa.Column('item_id', sa.String(length=36), nullable=True),
        sa.Column('supplier_id', sa.String(length=36), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', name='paymentstatus'), nullable=True),
        sa.Column('purchase_date', sa.DateTime(), nullable=False),
        sa.Column('payment_date', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['items.item_id']),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id']),
        sa.PrimaryKeyConstraint('purchase_id')
    )

    # Create stock table
    op.create_table(
        'stock',
        sa.Column('stock_id', sa.String(length=36), nullable=False),
        sa.Column('item_id', sa.String(length=36), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['items.item_id']),
        sa.PrimaryKeyConstraint('stock_id')
    )

    # Create payments table
    op.create_table(
        'payments',
        sa.Column('payment_id', sa.String(length=36), nullable=False),
        sa.Column('purchase_id', sa.String(length=36), nullable=True),
        sa.Column('method', sa.Enum('CASH', 'BANK', name='paymentmethod'), nullable=True),
        sa.Column('bank_account', sa.String(length=100), nullable=True),
        sa.Column('amount_paid', sa.Float(), nullable=True),
        sa.Column('is_paid', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['purchase_id'], ['purchases.purchase_id']),
        sa.PrimaryKeyConstraint('payment_id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('stock')
    op.drop_table('purchases')
    # ### end Alembic commands ###
