"""remove the unit price in purchase and sale item 

Revision ID: 34e31e5acab7
Revises: c4a89bfbed66
Create Date: 2025-08-01 01:31:07.884742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34e31e5acab7'
down_revision = 'c4a89bfbed66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
