"""changing

Revision ID: 48141506fb0b
Revises: 9a8c180bb285
Create Date: 2025-07-24 03:46:06.740990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48141506fb0b'
down_revision = '9a8c180bb285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))

  

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###
