"""Add all the tables and thier relations

Revision ID: 5739863d2213
Revises: a2db8310718c
Create Date: 2026-01-26 17:22:44.834844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5739863d2213'
down_revision: Union[str, Sequence[str], None] = 'efc84231ae75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'category_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('payments', sa.Column('purchase_invoice_id', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('sale_invoice_id', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'payments', 'sale_invoices', ['sale_invoice_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'purchase_invoices', ['purchase_invoice_id'], ['id'])
    op.drop_column('payments', 'invoice_type')
    op.drop_column('payments', 'invoice_id')
    op.alter_column('purchase_items', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('sale_items', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('stock_ledger', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('stock_ledger', 'ref_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_ledger', 'ref_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('stock_ledger', 'item_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('sale_items', 'item_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('purchase_items', 'item_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('payments', sa.Column('invoice_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('invoice_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'sale_invoice_id')
    op.drop_column('payments', 'purchase_invoice_id')
    op.alter_column('items', 'category_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
