"""increase_category_item_id_length

Revision ID: 8776f9b29451
Revises: 205f13854aa3
Create Date: 2026-01-27 01:35:12.661408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8776f9b29451'
down_revision: Union[str, Sequence[str], None] = '205f13854aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
