"""testing

Revision ID: 896a96aabdc5
Revises: 
Create Date: 2025-07-26 01:02:07.467601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896a96aabdc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=95), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('purchases',
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', name='paymentstatus'), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('stock',
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.Enum('CASH', 'BANK', name='paymentmethod'), nullable=True),
    sa.Column('bank_account', sa.Enum('MEEZAN', 'HBL', 'UBL', name='bankaccounts'), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.purchase_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('stock')
    op.drop_table('purchases')
    op.drop_table('suppliers')
    op.drop_table('items')
    op.drop_table('customers')
    # ### end Alembic commands ###
