"""add the credit/debit keys into the userProfile

Revision ID: 8c54c0b490ce
Revises: 6478841cf762
Create Date: 2026-01-24 13:19:35.529701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c54c0b490ce'
down_revision: Union[str, Sequence[str], None] = '6478841cf762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('total_transactions', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('total_paid', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'current_balance')
    op.drop_column('user_profiles', 'total_paid')
    op.drop_column('user_profiles', 'total_transactions')
    op.drop_column('user_profiles', 'company_name')
    op.drop_column('user_profiles', 'city')
    op.drop_column('user_profiles', 'phone')
    # ### end Alembic commands ###
