"""replace price with type

Revision ID: 9a8c180bb285
Revises: 2197d5a876d3
Create Date: 2025-07-24 03:15:25.951043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a8c180bb285'
down_revision = '2197d5a876d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('price')

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.create_index(batch_op.f('ix_items_item_id'), ['item_id'], unique=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
