"""add the field of unit_price in Stock

Revision ID: a5a10a6f7ab8
Revises: 896a96aabdc5
Create Date: 2025-07-26 01:21:59.968612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a10a6f7ab8'
down_revision = '896a96aabdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
