"""drop the column in the purchase

Revision ID: e8213308016e
Revises: 48141506fb0b
Create Date: 2025-07-24 03:56:43.499821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8213308016e'
down_revision = '48141506fb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###
