"""update the schema

Revision ID: efc84231ae75
Revises: a84aef8d71c7
Create Date: 2026-01-26 16:16:12.869271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc84231ae75'
down_revision: Union[str, Sequence[str], None] = 'a84aef8d71c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_accounts', 'type',
               existing_type=postgresql.ENUM('CASH', 'BANK', 'JAZZCASH', 'EASYPAISA', name='paymentaccounttype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_accounts', 'type',
               existing_type=postgresql.ENUM('CASH', 'BANK', 'JAZZCASH', 'EASYPAISA', name='paymentaccounttype'),
               nullable=True)
    # ### end Alembic commands ###
